// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RateMyCollegeClub.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(CollegeClubsDbContext))]
    [Migration("20250822182405_SeedClubs")]
    partial class SeedClubs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubTag", b =>
                {
                    b.Property<int>("ClubsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("ClubsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ClubTag", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RateMyCollegeClub.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FireBaseUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UniversityId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ClubLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UniversityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ClubLocation = "Engineering Center Basement, Room 100",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(7954),
                            Description = "",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Association for Computing Machinery",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            ClubLocation = "Livermore Center, Room 101",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(7965),
                            Description = "Software Engineering Club",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Society of Women Engineers",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            ClubLocation = "Whitacre College of Engineering, Room 205",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(7967),
                            Description = "Promoting Hispanic engineers and scientists in higher education and professional careers",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Society of Hispanic Professional Engineers",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            ClubLocation = "Recreation Center, Volleyball Courts",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(7969),
                            Description = "Competitive club volleyball for male students",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Tech Men's Club Volleyball",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            ClubLocation = "Recreation Center Climbing Wall",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(7970),
                            Description = "Rock climbing and bouldering club for all skill levels",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Tech Climbing Club",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            ClubLocation = "Student Union Building, Room 205",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(7971),
                            Description = "Celebrating Hispanic culture and heritage at Texas Tech",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Hispanic Student Society",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            ClubLocation = "International Cultural Center",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8012),
                            Description = "Promoting Korean culture and supporting Korean students at TTU",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Korean Student Association",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            ClubLocation = "Student Engagement Office, SUB 201",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8014),
                            Description = "Community service through American Red Cross initiatives",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "American Red Cross Society at Tech",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            ClubLocation = "Community Service Center",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8016),
                            Description = "Student organization focused on community service and volunteer work",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Raiders Helping Others",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            ClubLocation = "Student Union Building, Game Room",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8017),
                            Description = "Competitive and casual Super Smash Bros gaming community",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Super Smash Bros Club",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            ClubLocation = "Student Union Building, Recreation Area",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8018),
                            Description = "Board games, video games, and tabletop gaming community",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Tech Gaming Club",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            ClubLocation = "Student Media Building",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8020),
                            Description = "Texas Tech's student newspaper providing campus news and information",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Daily Toreador",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            ClubLocation = "College of Media & Communication",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8021),
                            Description = "Student organization for advertising and marketing professionals",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Tech Advertising Federation",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            ClubLocation = "Health Sciences Center, Room 3010",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8023),
                            Description = "Supporting pre-medical students in their journey to medical school",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Dr. Bernard Harris Pre-Medical Society",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            ClubLocation = "Rawls College of Business, Room 256",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8024),
                            Description = "Student ambassadors representing the Rawls College of Business",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Rawls College of Business Ambassadors",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 9,
                            ClubLocation = "School of Music, Band Hall",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8025),
                            Description = "Supporting the world's largest college marching band",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Goin' Band Student Association",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 9,
                            ClubLocation = "Recreation Center, Dance Studio",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8027),
                            Description = "Bollywood dance team celebrating South Asian culture through dance",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Tech Kahaani Bollywood Dance Team",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 10,
                            ClubLocation = "Political Science Building, Room 113",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8028),
                            Description = "Campus organization for Republican students and conservative politics",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Tech College Republicans",
                            Slug = "",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 11,
                            ClubLocation = "Baptist Student Center, 13th & University",
                            CreatedAt = new DateTime(2025, 8, 22, 18, 24, 5, 236, DateTimeKind.Utc).AddTicks(8029),
                            Description = "Faith-based community for Baptist students at Texas Tech",
                            IsActive = true,
                            LogoUrl = "",
                            Name = "Baptist Student Ministry",
                            Slug = "",
                            UniversityId = 1
                        });
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.ClubRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TagIdsJson")
                        .HasColumnType("text");

                    b.Property<int>("UniversityId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UniversityId");

                    b.HasIndex("UserId");

                    b.ToTable("ClubRequests");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InclusivityRating")
                        .HasColumnType("integer");

                    b.Property<int>("LeadershipRating")
                        .HasColumnType("integer");

                    b.Property<int>("NetScore")
                        .HasColumnType("integer");

                    b.Property<int>("NetworkingRating")
                        .HasColumnType("integer");

                    b.Property<decimal>("OverallRating")
                        .HasMaxLength(1000)
                        .HasColumnType("numeric");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SkillsDevelopmentRating")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.ReviewFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewFlags");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.SavedClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClubId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("ClubId1");

                    b.HasIndex("UserId");

                    b.ToTable("SavedClubs");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficialWebsite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.UniversityRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficialWebsite")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UniversityRequests");
                });

            modelBuilder.Entity("TagUser", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.HasKey("TagsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserTag", (string)null);
                });

            modelBuilder.Entity("server.Models.ReviewVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewVotes");
                });

            modelBuilder.Entity("ClubTag", b =>
                {
                    b.HasOne("RateMyCollegeClub.Models.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateMyCollegeClub.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RateMyCollegeClub.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RateMyCollegeClub.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateMyCollegeClub.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RateMyCollegeClub.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RateMyCollegeClub.Data.User", b =>
                {
                    b.HasOne("RateMyCollegeClub.Models.University", "University")
                        .WithMany("Users")
                        .HasForeignKey("UniversityId");

                    b.Navigation("University");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.Club", b =>
                {
                    b.HasOne("RateMyCollegeClub.Models.Category", "Category")
                        .WithMany("Clubs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateMyCollegeClub.Models.University", "University")
                        .WithMany("Clubs")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("University");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.ClubRequest", b =>
                {
                    b.HasOne("RateMyCollegeClub.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateMyCollegeClub.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateMyCollegeClub.Data.User", "User")
                        .WithMany("ClubRequests")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.Review", b =>
                {
                    b.HasOne("RateMyCollegeClub.Models.Club", "Club")
                        .WithMany("Reviews")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateMyCollegeClub.Data.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.ReviewFlag", b =>
                {
                    b.HasOne("RateMyCollegeClub.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateMyCollegeClub.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.SavedClub", b =>
                {
                    b.HasOne("RateMyCollegeClub.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateMyCollegeClub.Models.Club", null)
                        .WithMany("SavedByUsers")
                        .HasForeignKey("ClubId1");

                    b.HasOne("RateMyCollegeClub.Data.User", "User")
                        .WithMany("SavedClubs")
                        .HasForeignKey("UserId");

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.UniversityRequest", b =>
                {
                    b.HasOne("RateMyCollegeClub.Data.User", "User")
                        .WithMany("UniversityRequests")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TagUser", b =>
                {
                    b.HasOne("RateMyCollegeClub.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateMyCollegeClub.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.Models.ReviewVote", b =>
                {
                    b.HasOne("RateMyCollegeClub.Models.Review", "Review")
                        .WithMany("Votes")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RateMyCollegeClub.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RateMyCollegeClub.Data.User", b =>
                {
                    b.Navigation("ClubRequests");

                    b.Navigation("Reviews");

                    b.Navigation("SavedClubs");

                    b.Navigation("UniversityRequests");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.Category", b =>
                {
                    b.Navigation("Clubs");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.Club", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.Review", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("RateMyCollegeClub.Models.University", b =>
                {
                    b.Navigation("Clubs");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
